---
  - hosts: all
    tasks:
      - name: Update apt cache.
        apt: update_cache=yes cache_valid_time=3600
        when: ansible_os_family == 'Debian'
      - name: Install docker
        apt:
          install_recommends: false
          name: docker
      - name: Ensure docker group
        group:
          name: docker
      - name: Add vagrant user to docker group.
        user:
          name: vagrant
          groups: docker
          append: true
