---
# roles/common/tasks/main.yml

- name: Add required Ubuntu packages
  import_tasks: packages.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Add  vagrant box users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop:
    - vagrant # TODO: expose as var
    - ubuntu

- name: Create application directory hierarchy
  file:
    path: /opt/compose
    state: directory
    mode: '0754'
    recurse: yes
    owner: vagrant # TODO: expose as var
    group: vagrant # TODO: expose as var

# TODO: expose network prefix as var (ipv4.address match)
- name: Set internal_network_device fact
  set_fact:
    internal_network_device: "{{ ansible_facts | dict2items | selectattr('value.ipv4', 'defined') | selectattr('value.ipv4.address', 'match', '^192.168.5') | first }}"
    cacheable: yes

- name: Check internal network ipv4 fact
  debug:
    msg: "HOST_IP={{ internal_network_device.value.ipv4.address }}"

- name: Create systemd service template /etc/systemd/system/compose@.service
  template:
    src: roles/common/templates/compose@.service.j2
    dest: /etc/systemd/system/compose@.service
    owner: root
    group: root
    mode: '0755'
