- debug:
    var: item

- name: "Create {{ item.id }} compose directory"
  file:
    path: "/opt/compose/{{ item.id }}"
    state: directory
    mode: '0755'
    owner: vagrant # TODO: expose as var
    group: vagrant # TODO: expose as var

- name: "Generate {{ item.id }} component compose file"
  template:
    src: templates/cms/cms-compose.yml.j2
    dest: "/opt/compose/{{ item.id }}/docker-compose.yml"
    owner: vagrant # TODO: expose as var
    group: vagrant # TODO: expose as var
    mode: '0755'
  vars:
    container_command: "{{ item.command|default('help') }}"
    container_envs: "{{ item.envs }}"

- debug: "msg=Start {{ item.id }} compose"

- name: Start {{ item.id }} compose
  service:
    name: compose@{{ item.id }}
    state: started
