# -*- mode: ruby -*-
# vi: set ft=ruby :
# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

Vagrant.configure("2") do |config|
  #   https://app.vagrantup.com/ubuntu/boxes/focal64
  VM_IMAGE_NAME = "ubuntu/focal64"
  VM_IMAGE_VERSION = "20200804.0.0"

  (1..3).reverse_each do |node_number|
    vm_name = "node00#{node_number}"

    config.vm.define vm_name do |node|
      ##
      # Vagrant Box base image
      #
      # VM image build history ->
      ##
      node.vm.box = VM_IMAGE_NAME
      node.vm.box_version = VM_IMAGE_VERSION
      node.vm.box_check_update = false

      ##
      # Network configurations
      ##
      node.vm.hostname  = vm_name

      # Access to Edge VM port 80 as localhost:8000
      # node.vm.network "forwarded_port", guest: 80, host: 8000 if node_number == 1

      # Reach VM as an specific private IP
      node.vm.network "private_network", ip: "192.168.5.#{10+node_number}", hostsupdater: "skip"

      ##
      # VirtualBox VM customization
      ##
      node.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = "1516"
      end

      ##
      # Provisioning
      ##

      # Add nodes list to /etc/host file
      node.vm.provision "shell", inline: <<~EOS
      { \
        echo '192.168.5.11 node001.cms-orbits.com node001 orbits edge'; \
        echo '192.168.5.12 node002.cms-orbits.com node002 cms'; \
        echo '192.168.5.13 node003.cms-orbits.com node003 postgres mongo rabbit'; \
      } >> /etc/hosts
      EOS

      if node_number == 1
        # Copy other machines Vagrant generate private keys
        Dir.glob(".vagrant/machines/**/virtualbox/private_key").each do | p |
            name = p.gsub('.vagrant/machines/','').gsub('/','-')
            node.vm.provision "file", source: p, destination: "/home/vagrant/.ssh/#{name}"
        end

        # Copy Ansible files
        node.vm.provision "file", source: "ansible/", destination: "/home/vagrant"

        # Ensure python3 and pip are installed on Ansible controller host
        node.vm.provision "shell", inline: <<~EOS
          apt-get update
          apt-get install -y python3 python3-pip
        EOS

        # Provision all the machines using Ansible
        node.vm.provision "ansible_local" do |ansible|
          ansible.install_mode = "pip"
          ansible.playbook = "/home/vagrant/playbook.yml"
          ansible.inventory_path = "/home/vagrant/inventory"
          ansible.config_file = "/home/vagrant/ansible.cfg"
          ansible.limit = "all" # or only "nodes" group, etc.
          ansible.become = true
          ansible.verbose = true
        end
      end

      # Apply all the provision scripts.
      # WARNING: The provision scripts are hardly coupled to the provision-files directory path
      # provision_scripts = case i
      # when 1 # Edge / Orbits
      #     %w(00-install-prerequisites.sh 01-docker-services.sh 05-docker-nginx-edge.sh 08-docker-cms-orbits.sh)
      # when 2 # CMS
      #     %w(00-install-prerequisites.sh 01-install-compilers.sh 01-docker-services.sh 03-populate-cms-database.sh 04-cms-compilers.sh 04-docker-cms.sh)
      # when 3 # Data
      #     %w(00-install-prerequisites.sh 01-docker-services.sh 02-docker-postgresql.sh 06-docker-rabbitmq.sh 07-docker-mongodb.sh)
      # else
      #     []
      # end
    end
  end
end
